/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
    const { nodes, materials } = useSpline('https://prod.spline.design/iOuxVjXhttn6BXLO/scene.splinecode')
    return (
        <>
            <color attach="background" args={['#74757a']} />
            <group {...props} dispose={null}>
                <scene name="Scene 1">
                    <mesh
                        name="Cube"
                        geometry={nodes.Cube.geometry}
                        material={materials['Cube Material']}
                        skeleton={nodes.Cube.skeleton}
                        castShadow
                        receiveShadow
                        position={[158.23, 18.77, 681.5]}
                        scale={[-0.1, 0.1, 0.1]}
                    >
                        <mesh
                            name="Rectangle 6"
                            geometry={nodes['Rectangle 6'].geometry}
                            material={materials['Rectangle 6 Material']}
                            skeleton={nodes['Rectangle 6'].skeleton}
                            castShadow
                            receiveShadow
                            position={[1.09, -190.5, 1.83]}
                            rotation={[Math.PI / 2, 0, 0]}
                        />
                        <mesh
                            name="Rectangle 5"
                            geometry={nodes['Rectangle 5'].geometry}
                            material={materials['Rectangle 5 Material']}
                            skeleton={nodes['Rectangle 5'].skeleton}
                            castShadow
                            receiveShadow
                            position={[-190.5, 1.99, 0]}
                            rotation={[0, -Math.PI / 2, 0]}
                        />
                        <mesh
                            name="Rectangle 4"
                            geometry={nodes['Rectangle 4'].geometry}
                            material={materials['Rectangle 4 Material']}
                            skeleton={nodes['Rectangle 4'].skeleton}
                            castShadow
                            receiveShadow
                            position={[0.5, 3, 190.5]}
                        />
                        <mesh
                            name="Rectangle 3"
                            geometry={nodes['Rectangle 3'].geometry}
                            material={materials['Rectangle 3 Material']}
                            skeleton={nodes['Rectangle 3'].skeleton}
                            castShadow
                            receiveShadow
                            position={[190.5, 3.01, 2]}
                            rotation={[0, Math.PI / 2, 0]}
                        />
                        <mesh
                            name="Rectangle 2"
                            geometry={nodes['Rectangle 2'].geometry}
                            material={materials['Rectangle 2 Material']}
                            skeleton={nodes['Rectangle 2'].skeleton}
                            castShadow
                            receiveShadow
                            position={[1.57, 2.41, -190.5]}
                            rotation={[-Math.PI, 0, -Math.PI]}
                        />
                        <mesh
                            name="Rectangle"
                            geometry={nodes.Rectangle.geometry}
                            material={materials['Rectangle Material']}
                            skeleton={nodes.Rectangle.skeleton}
                            castShadow
                            receiveShadow
                            position={[1.16, 190.5, 1.25]}
                            rotation={[-Math.PI / 2, 0, 0]}
                        />
                    </mesh>
                    <directionalLight
                        name="Directional Light"
                        castShadow
                        intensity={0.7}
                        shadow-mapSize-width={1024}
                        shadow-mapSize-height={1024}
                        shadow-camera-near={-10000}
                        shadow-camera-far={100000}
                        shadow-camera-left={-1000}
                        shadow-camera-right={1000}
                        shadow-camera-top={1000}
                        shadow-camera-bottom={-1000}
                        position={[200, 300, 300]}
                    />
                    <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
                    <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
                </scene>
            </group>
        </>
    )
}

